development:
  adapter: mysql2
  encoding: utf8
  database: iblog_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: iblog_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: iblog2
  pool: 5
  username: iblog
  password: sushf2819s
  socket: /var/run/mysqld/mysqld.sock
