development:
  encoding: utf8
  adapter: sqlite3
  database: db/dev.sqlite

test:
  encoding: utf8
  adapter: sqlite3
  database: db/test.sqlite

production:
  encoding: utf8
  adapter: sqlite3
  database: db/production.sqlite
